name = "treehouse"

[applications]

[applications.rust]
manifest = "experimental/treehouse/application/oak_app_manifest.toml"
out = "experimental/treehouse/application/bin/treehouse.oak"

[applications.rust.modules]
module = { Cargo = { cargo_manifest = "experimental/treehouse/application/module/Cargo.toml" } }

[server]
additional_args = [
  "--config-files=config=experimental/treehouse/application/config.toml"
]

[clients]
rust = { Cargo = { cargo_manifest = "experimental/treehouse/application/client/Cargo.toml" }, additional_args = [
  "--root-tls-certificate=examples/certs/local/ca.pem",
] }
